### ISSUE TITLE
Need Video components to accept only YouTube links

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-co-nz#1]
Need to have all the Video Components that we currently use on US site to accept only YouTube Videos for NZ.

**Comment by BeckyMedlin** [comment]
@manuel-vara -- Per discussion today with Wendy and @Joesturbo, can we remove the restriction to require YouTube and AEM video and, if so, what's the impact to the cookie handler and is there any work required? Thank you!

**Comment by manuel-vara** [comment]
To confirm, finally the variation update would be this block only working with the local mp4 video and the YouTube link would not be necessary, correct?

**Comment by Gonzalo-CG** [comment]
It was decided that the block should have all 3 options, i.e.:

- Current one (Block has both a YouTube & an AEM link).
- Block has only a YouTube link.
- Block has only an AEM link.

**Comment by girishdigrajkar** [comment]
Understood from Jonatan that this ticket is still under development so changing the status accordingly.

**Comment by girishdigrajkar** [comment]
Validated and able to get the desired results hence, marking this ticket to done status:

Test URL :   https://1-video-block-multiple-choice--vg-macktrucks-co-nz--hlxsites.hlx.page/drafts/jlledo/embed-demo
