### ISSUE TITLE
NFR: Configure analytics/tracking (GTM, FB Pixel)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-co-nz#10]
This is part of the GoLive activities.

**Comment by manuel-vara** [comment]
GTM Code of NZ:  **GTM-WG2G4RL**

**Comment by Kannan-CM** [comment]
OneTrust script for NZ:


<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="2944b66f-af0b-465f-8e2a-1806f036dbcf" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="2944b66f-af0b-465f-8e2a-1806f036dbcf" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
Those are the scripts for OneTrust
