### ISSUE TITLE
GoLive Activities Checklist - MackTrucks NZ 

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-co-nz#11]
Checklist of all activities needed for the GoLive of MackTrucks.co.nz:

**Pre, during and post-GoLive:**
- [x] #9 

**Pre-GoLive:**
- [x] #5 
- [x] #6
- [x] #7 
- [x] #8 
- [x] #10
- [ ] [AEM GoLive steps](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- Legacy redirects
- Favicon
- CDN configuration
- Update production host

**Post-GoLive:**
- [ ] [AEM Post-GoLive Validation](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- 404 Report

**Comment by Kannan-CM** [comment]
NZ content looks good. So closing the ticket.
