### ISSUE TITLE
Nav issue

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-co-nz#18]
Hi Team,

We are trying to update the link text on the main Nav from "Built in Australia" to "Built for New Zealand".
When we do the buldog icon and the "Find My Dealer" background color disappears.

![image](https://github.com/hlxsites/vg-macktrucks-co-nz/assets/126496977/977584d3-65d3-481d-8ed8-89163d402e5b)

Could you please help us with the changes. Also the links for Engines and Transmission dont appear under the "Powertrain" menu

![image](https://github.com/hlxsites/vg-macktrucks-co-nz/assets/126496977/38176917-8638-4e23-841b-957155ecccd9)

**Comment by jonatan-lledo-netcentric** [comment]
Fixed, it was just content
Header is a complex component spread across all the document.
so 1st link has to be updated, but also...


![Image](https://github.com/hlxsites/vg-macktrucks-co-nz/assets/117984204/7f6e6bcf-556b-4815-9fdc-8ec967b32579)

... the 2nd and the 3rd links also need to be updated/copied from the 1st one



![Image](https://github.com/hlxsites/vg-macktrucks-co-nz/assets/117984204/1e44fb3e-d659-4012-b34c-8456a2519884)

**Comment by DanielaPedrochevd** [comment]
@Kannan-CM

**Comment by jonatan-lledo-netcentric** [comment]
for the powertrain titles is needed to style the text first as header 3. Then select the whole line and then add the link. if the steps are corrected done, then the title will be shown

**Comment by Kannan-CM** [comment]
Thank you @jonatan-lledo-netcentric we will try that.

Also we need to enable Search icon for NZ and AU. Woudl you be able to help us with that?

**Comment by Kannan-CM** [comment]
Thank you @jonatan-lledo-netcentric the header changes works.

Woudl you be able to share a document on what is needs for the header and footer? just like a check list for us to refer time and again?

**Comment by jonatan-lledo-netcentric** [comment]
I don't have any documentation; I'm just following how it's coded, and I check the console log errors using the inspector. That's what I did. As simple as that.
