### ISSUE TITLE
Macktrucks NZ Site consolidated issues

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-co-nz#20]
**Macktrucks NZ Site consolidated issues** 

1. Homepage >> Navigation >> Parts & Services  menu is not in new format  
  Below sub menu pages are not authored/published 
Mac-connect.  https://www.macktrucks.co.nz/parts-and-services/mack-telematics/
	
2.  Homepage >> Navigation >> Built for New Zealand >>.      Link name is not Experience / Not all menus are displayed as [macktrucks.com](http://macktrucks.com/) 
3.  Homepage >> Navigation >>  Trucks >> Mack Lineup >>    ‘Build yours’ & ‘See Incentives >’  links are not present for any Truck model 
4.  Homepage >> Navigation >>  Trucks >> Mack Lineup >>   Registered trademark is not present for all truck models; ensure as per applicability;
5.  Homepage>> Footer is incorrect  X, Instagram icons are not present ;  Below links are not present :		
                [About Mack](https://www.macktrucks.com/about-mack/)
		[Mack News](https://www.macktrucks.com/mack-news/)
		[Change Country](https://www.macktrucks.com/splash/)
		[Careers](https://www.macktrucks.com/about-mack/careers/)
		[Body Builder](https://www.macktrucks.com/parts-and-services/support/body-builders/)
		[2023 Labor Negotiations](https://www.macktrucks.com/mack-news/2023/uaw-members-ratify-agreement-with-mack-trucks)
		[Emissions Info](https://www.macktrucks.com/parts-and-services/sir-emissions-information/)
		[SDS Info](https://www.macktrucks.com/parts-and-services/parts/mack-parts/material-safety-data-sheets)
		[Safety Recalls](https://www.macktrucks.com/recalls/)
		[Contact Us](https://www.macktrucks.com/about-mack/contact-us/)
		[Cookies](https://www.macktrucks.com/cookies/)
		[Terms & Conditions](https://www.macktrucks.com/public-privacy-policy/terms-of-use)
		[Do Not Sell or Share My Personal Information](https://www.volvogroup.com/en/tools/privacy/data-subject-rights.html)
6. Cookie setting icon at left bottom of homepage is different than macktracks.com
7. The pre-footer has ‘Contact Mack ->’  link whereas that on ,[macktracks.com](http://macktracks.com/)  has ‘Build My Mack’,  ‘Find My Dealer’ & ‘Request a Quote’ links
8.  Homepage >>  Trucks >> Powertrain >>  Axles, Suspensions, Exhaust Aftertreatment Systems  cards/links are not present 
9. Mobile :    Homepage  Explore container does not have ‘Find a dealer’ accordian ;     
                    ‘Contact us’  text in accordion is not capital unlike other accordions 
10. Homepage :  Does not have Mack Connect’ promo block, ‘Mack Stories’ section cards , ‘Community’ Section cards instead have 2 YouTube videos.

**Comment by Kannan-CM** [comment]
Hi @girishdigrajkar,

Thank you for sharing the consolidated list. 

NZ has different content compared to the US site, that is the reason you some pages are not present on the NZ site.

We have addressed the Mack Icon issue on the bottom left of the page.

We are good to close this ticket.

**Comment by jonatan-lledo-netcentric** [comment]
1. it's ok because it has less content than the `.com` version
2, 3, 7, 8 & 10. it's ok because is the NZ version
4. in the legacy [page](https://nz.mackprod-cm.na.volvogroup.com/trucks/) none of the all models has the TM icon 
5. No NZ tweeter/X, Instagram added.
>- About Mack
>- Careers
>- Contact Us

are already present in header & footer
>- Mack News
>- Body Builder
>- 2023 Labor Negotiations
>- Emissions Info
>- SDS Info
>- Safety Recalls
>- Cookies
>- Terms & Conditions
>- Do Not Sell or Share My Personal Information

Not used or not implemented the page content
> Change Country

is present but in another position, like the other export markets

6. cookie icon is fixed
9. now all explore block title items are uppercase in any portrait

@girishdigrajkar please, take a look.

**Comment by shirin27** [comment]
@Kannan-CM can you please re-test and close this issue if all is resolved?
thank you!

**Comment by Kannan-CM** [comment]
NZ content are good.
