### ISSUE TITLE
Magazine category pages displaying 0 when no truck is selected

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-co-nz#23]
1. Magazine section cards are showing 0 when no trucks are selected.
2. Null appears at the bottom of every Magazine article
3. The category pages do not show all the articles tagged with the category name:
Example: https://www.macktrucks.co.nz/magazine/categories/viewpoint

Viewpoint has 9 articles only 5 shows on the page.

**Comment by santi-homps** [comment]
Item 3 has been sorted as a content issue and it is closed.

**Comment by santi-homps** [comment]
Item 1 was due to wrong content in metadata of 1 article.

**Comment by santi-homps** [comment]
Item 2 will be solved with issue [733](https://github.com/hlxsites/vg-macktrucks-com/issues/733)

**Comment by ZoeBeykirch** [comment]
Closing ticket as this has been fixed in production.
