### ISSUE TITLE
Dealer page on New Zealand website is down

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-co-nz#26]
### Issue Type

Defect

### Priority

Blocker

### Description

The marketing lead for Mack Trucks NZ reported that the dealer locator page is not working. They also reported that there were broken links on the map.

### Affected Device Classes

Mobile, Desktop

### Affected Browsers/Devices and Versions

Chrome v130.0.6723.70 in Windows 11

### Steps to Reproduce

Go to the dealer locator in Mack Trucks NZ

### Expected Results

To see the dealer locator in Mack Trucks NZ

### Actual Results

Nothing is shown when I try to find the Mack Trucks NZ site

**Comment by KJohnsn** [comment]
[market-export-dealer.xlsx](https://github.com/user-attachments/files/17599949/market-export-dealer.xlsx)
dealer information is located in the spreadsheet

**Comment by santi-homps** [comment]
@Kannan-CM When doing the helix-5 upgrade, the old dealer-locator blocks should be changed to the new v2-dealer-locator blocks.

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.
