### ISSUE TITLE
Trucks product page is showing a white page

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-co-nz#27]
### Issue Type

Bug

### Summary

The Trucks Product page is not showing

### Priority

Blocker

### Description

When I checked the Mack Trucks NZ site to see if I could locate specific areas in the site, the Trucks product page doesn't load and we see a white page instead. The products for this market must be shown at all times.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Chrome v130.0.6723.70 on Windows 11

### Steps to Reproduce

Go to https://www.macktrucks.co.nz/trucks/
Wait for the page to load

### Expected Results

The page loads showing the trucks that are available for the NZ market.

### Actual Results

A blank, white page is shown

### Attachment

![mack trucks nz white page](https://github.com/user-attachments/assets/610679ac-2867-4751-baf5-063415d56953)

**Comment by BeckyMedlin** [comment]
Closing - Issue appears to be resolved.
