### ISSUE TITLE
Testing: Site testing for MackTrucks NZ (QA & UAT) - Spillover

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-co-nz#9]
Testing in full all pages/sections of the site. 
This issue is for both QA testing and UAT.

**Comment by DanielaPedrochevd** [comment]
Spillover due to content which is expected to be ready by 22/11

**Comment by girishdigrajkar** [comment]
Validated NZ site for Hompage validations only ( As Find a Dealer changes are in progress by dev team & find a dealer link not configured by content team on NZ site yet) ;  Raised [issue 20](https://github.com/hlxsites/vg-macktrucks-co-nz/issues/20) for consilidated list of issues observed

**Comment by Kannan-CM** [comment]
Contnet looks good on NZ site
